openapi: 3.0.0
info:
  title: GreatReads API Gateway
  description: Unified API for GreatReads platform
  version: 1.0.0

servers:
  - url: http://localhost:3000

paths:
  /api/users/register:
    post:
      summary: Register a new user
      tags: [Users]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - email
                - password
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: User registered successfully
        "400":
          description: Invalid input

  /api/users/login:
    post:
      summary: Login user
      tags: [Users]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login successful
        "401":
          description: Invalid credentials

  /api/books/reading:
    post:
      summary: Add a book to user's reading list
      tags: [Books]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - bookId
              properties:
                bookId:
                  type: string
                progress:
                  type: integer
                  default: 0
                status:
                  type: string
                  example: reading
      responses:
        "201":
          description: Book added successfully
        "400":
          description: Invalid input
        "401":
          description: Unauthorized (invalid or missing token)
        "500":
          description: Internal server error

    get:
      summary: Get user's reading list
      tags: [Books]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: List of books
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    userId:
                      type: string
                    bookId:
                      type: string
                    progress:
                      type: integer
                    status:
                      type: string
        "401":
          description: Unauthorized (invalid or missing token)
        "500":
          description: Internal server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
