openapi: 3.0.0
info:
  title: GreatReads Book Service API
  description: API for managing user reading lists and reading progress
  version: 1.0.0

servers:
  - url: http://localhost:3002

paths:
  /api/books/search:
    get:
      summary: Buscar libros en Google Books
      tags: [Books]
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: q
          required: true
          schema:
            type: string
          description: Término de búsqueda para libros
      responses:
        "200":
          description: Lista de libros encontrados
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    bookId:
                      type: string
                    title:
                      type: string
                    authors:
                      type: array
                      items:
                        type: string
                    description:
                      type: string
                    publisher:
                      type: string
                    publishedDate:
                      type: string
                    pageCount:
                      type: integer
                    thumbnail:
                      type: string
        "401":
          description: Unauthorized
        "500":
          description: Internal server error

  /api/books/reading:
    post:
      summary: Añadir un libro a la lista de lectura
      tags: [Books]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - bookId
              properties:
                bookId:
                  type: string
                progress:
                  type: integer
                  default: 0
                status:
                  type: string
                  example: reading
      responses:
        "201":
          description: Libro añadido correctamente
        "400":
          description: Invalid input
        "401":
          description: Unauthorized
        "500":
          description: Internal server error

    get:
      summary: Obtener la lista de lectura del usuario con info completa
      tags: [Books]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Lista de libros con información completa
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    bookId:
                      type: string
                    title:
                      type: string
                    authors:
                      type: array
                      items:
                        type: string
                    description:
                      type: string
                    publisher:
                      type: string
                    publishedDate:
                      type: string
                    pageCount:
                      type: integer
                    thumbnail:
                      type: string
                    progress:
                      type: integer
                    status:
                      type: string
        "401":
          description: Unauthorized
        "500":
          description: Internal server error